
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: setup gcloud sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}
          service_account_key: ${{secrets.GCP_SA_KEY}}
          export_default_credentials: true
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: mvn clean install

      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{secrets.GCR_JSON_KEY}}
      - name: docker build
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          file: ./Dockerfile
          tags: gcr.io/${{secrets.GCP_PROJECT_ID}}/quotes:latest
